export const items =[
    {id:1,title:"launch meal",description:"Normally <Button> components will render a HTML <button> element. However you can render whatever you'd like, adding a href prop will automatically render an <a /> element. You can use the as prop to render whatever your heart desires. React Bootstrap will take care of the proper ARIA roles for you.",price:"100 EGP",category:"launch",imgURL:"img1.jpg"},
    {id:2,title:"breakfast meal",description:"Normally <Button> components will render a HTML <button> element. However you can render whatever you'd like, adding a href prop will automatically render an <a /> element. You can use the as prop to render whatever your heart desires. React Bootstrap will take care of the proper ARIA roles for you.",price:"100 EGP",category:"breakfast",imgURL:"img2.jpg"},
    {id:3,title:"launch meal",description:"Normally <Button> components will render a HTML <button> element. However you can render whatever you'd like, adding a href prop will automatically render an <a /> element. You can use the as prop to render whatever your heart desires. React Bootstrap will take care of the proper ARIA roles for you.",price:"100 EGP",category:"launch",imgURL:"img2.jpg"},
    {id:4,title:"dinner meal",description:"Normally <Button> components will render a HTML <button> element. However you can render whatever you'd like, adding a href prop will automatically render an <a /> element. You can use the as prop to render whatever your heart desires. React Bootstrap will take care of the proper ARIA roles for you.",price:"100 EGP",category:"dinner",imgURL:"img4.jpg"},
    {id:5,title:"breakfast meal",description:"Normally <Button> components will render a HTML <button> element. However you can render whatever you'd like, adding a href prop will automatically render an <a /> element. You can use the as prop to render whatever your heart desires. React Bootstrap will take care of the proper ARIA roles for you.",price:"100 EGP",category:"breakfast",imgURL:"img1.jpg"},
    {id:6,title:"breakfast meal",description:"Normally <Button> components will render a HTML <button> element. However you can render whatever you'd like, adding a href prop will automatically render an <a /> element. You can use the as prop to render whatever your heart desires. React Bootstrap will take care of the proper ARIA roles for you.",price:"100 EGP",category:"breakfast",imgURL:"img2.jpg"},
    {id:7,title:"launch meal",description:"Normally <Button> components will render a HTML <button> element. However you can render whatever you'd like, adding a href prop will automatically render an <a /> element. You can use the as prop to render whatever your heart desires. React Bootstrap will take care of the proper ARIA roles for you.",price:"100 EGP",category:"breakfast",imgURL:"img4.jpg"},
    {id:8,title:"dinner meal",description:"Normally <Button> components will render a HTML <button> element. However you can render whatever you'd like, adding a href prop will automatically render an <a /> element. You can use the as prop to render whatever your heart desires. React Bootstrap will take care of the proper ARIA roles for you.",price:"100 EGP",category:"dinner",imgURL:"img1.jpg"},
    {id:9,title:"breakfast meal",description:"Normally <Button> components will render a HTML <button> element. However you can render whatever you'd like, adding a href prop will automatically render an <a /> element. You can use the as prop to render whatever your heart desires. React Bootstrap will take care of the proper ARIA roles for you.",price:"100 EGP",category:"breakfast",imgURL:"img3.jpg"}

]